# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployHostPool
  jobs:
  - job: DefineTokenExpirationTime
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './arm-wvd-CreateAndProvisionHostPool/createhostpoolExpirationTime.ps1'
  - job: DeployResources
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'bs-dev-sub'
          subscriptionId: 'caf17c93-b390-4f78-a96f-4e6a4a34546a'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '_wvd_demo-01'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: './arm-wvd-CreateAndProvisionHostPool/wvd-demo-CreateAndProvisionHostPool.json'
          csmParametersFile: './arm-wvd-CreateAndProvisionHostPool/wvd-demo-CreateAndProvisionHostPool.parameters.json'
          overrideParameters: '-administratorAccountUsername $(bs-DomainAdminUser) -administratorAccountPassword $(bs-DomainAdminPassword) -tokenExpirationTime $(ExpirationTime)'
          deploymentMode: 'Incremental'
          deploymentName: '_wvd_demo_01_hp_deployment'
